#!/bin/bash

set -euox pipefail;

PYTHON="python"
if [ -f "Dockerfile" ]; then
    PYTHON=$(grep "FROM python" Dockerfile | head -n1 | sed 's/FROM \(python:[^- ]*\).*/\1/g')
    echo "Found python version: ${PYTHON}"
fi

if [ "$#" -eq 0 ]; then
    createMambaEnv $(basename $(pwd)) ${PYTHON/:/=} pip -y
else
    createMambaEnv $1 ${PYTHON/:/=} pip -y
fi
